# NumPy

* verwaltet effizient Arrays/Matrizen/Tensoren in `ndarray`
* ![Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)
* im Hintergrund hochperformantes C
* Elemente eines Arrays sind vom selben Datentyp
* Standardalias `np`
* Operationen werden meist auf ganze Arrays angewandt (*Broadcasting*)

### Vokabel

* `axis`/`axes` - Dimension
* `dtype` - Datentyp
* `shape` - Tupel, das die Form des Arrays beschreibt

In [2]:
import numpy as np

### Erzeugung

In [2]:
array = np.array([42, 3.1415])
print(array, array.shape, array.dtype, type(array))

[42.      3.1415] (2,) float64 <class 'numpy.ndarray'>


In [9]:
matrix = np.arange(0, 24, 2)
print(matrix)
matrix = matrix.reshape(2, 6)
print(matrix, matrix.shape)
matrix.reshape(6, -1) # -1 => was sich ausgeht

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]] (2, 6)


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [16]:
x = np.linspace(0, np.pi, 20) # für floats besser geeignet als arange
print(x, x.shape)
sin = np.sin(x)
print(sin)

[0.         0.15707963 0.31415927 0.4712389  0.62831853 0.78539816
 0.9424778  1.09955743 1.25663706 1.41371669 1.57079633 1.72787596
 1.88495559 2.04203522 2.19911486 2.35619449 2.51327412 2.67035376
 2.82743339 2.98451302 3.14159265] (21,)
[0.00000000e+00 1.56434465e-01 3.09016994e-01 4.53990500e-01
 5.87785252e-01 7.07106781e-01 8.09016994e-01 8.91006524e-01
 9.51056516e-01 9.87688341e-01 1.00000000e+00 9.87688341e-01
 9.51056516e-01 8.91006524e-01 8.09016994e-01 7.07106781e-01
 5.87785252e-01 4.53990500e-01 3.09016994e-01 1.56434465e-01
 1.22464680e-16]


### Ausgabe

* Arrays als []
* Matrizen als 
  ```python
  [[
   []
  ]]
  ```
* Tensoren mit leerzeilen zwischen slices

In [27]:
array = np.arange(24)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [26]:
matrix = array.reshape(4, 6)
print(matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [28]:
tensor = matrix.reshape(3, 2, 4)
print(tensor)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


### Slicing

* wie bei Listen
* bei mehreren Dimensionen Indices als Tupel
* Index kann selbst Liste sein

In [10]:
matrix = np.arange(0,12).reshape(3,4)
matrix = 2**matrix
print(matrix)

[[   1    2    4    8]
 [  16   32   64  128]
 [ 256  512 1024 2048]]


In [16]:
#print(matrix[1, 1])
#print(matrix[1, :])
#print(matrix[1])
#print(matrix[:, 1])
#print(matrix[::2, 0:2])
print(matrix[[1, 2], 1])

[ 32 512]


### Conditional selection/Boolean indexing

* effektive filter-Methode

In [33]:
matrix = np.arange(0,12).reshape(3, 4)
print(matrix)
is_even = matrix % 2 == 0
print(is_even)
even_elements = matrix[is_even]
print(even_elements)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[ 0  2  4  6  8 10]


In [38]:
matrix[matrix > 7]

array([ 8,  9, 10, 11])

In [29]:
a = np.random.randint(30, size=10)
a

array([ 7, 19, 15,  3, 19,  4,  1,  3, 29, 16])

In [35]:
a.argmax()

8